# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tapp.proto\"\x1a\n\nAppRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0b\x41ppResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t2\xd1\x01\n\x0b\x41pplication\x12*\n\x0bGetResponse\x12\x0b.AppRequest\x1a\x0c.AppResponse\"\x00\x12\x34\n\x13GetStreamedResponse\x12\x0b.AppRequest\x1a\x0c.AppResponse\"\x00\x30\x01\x12-\n\x0cGetResponse1\x12\x0b.AppRequest\x1a\x0c.AppResponse\"\x00(\x01\x12\x31\n\x0eMultipleStream\x12\x0b.AppRequest\x1a\x0c.AppResponse\"\x00(\x01\x30\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_APPREQUEST = _descriptor.Descriptor(
  name='AppRequest',
  full_name='AppRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='AppRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=39,
)


_APPRESPONSE = _descriptor.Descriptor(
  name='AppResponse',
  full_name='AppResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='AppResponse.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['AppRequest'] = _APPREQUEST
DESCRIPTOR.message_types_by_name['AppResponse'] = _APPRESPONSE

AppRequest = _reflection.GeneratedProtocolMessageType('AppRequest', (_message.Message,), dict(
  DESCRIPTOR = _APPREQUEST,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:AppRequest)
  ))
_sym_db.RegisterMessage(AppRequest)

AppResponse = _reflection.GeneratedProtocolMessageType('AppResponse', (_message.Message,), dict(
  DESCRIPTOR = _APPRESPONSE,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:AppResponse)
  ))
_sym_db.RegisterMessage(AppResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ApplicationStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetResponse = channel.unary_unary(
          '/Application/GetResponse',
          request_serializer=AppRequest.SerializeToString,
          response_deserializer=AppResponse.FromString,
          )
      self.GetStreamedResponse = channel.unary_stream(
          '/Application/GetStreamedResponse',
          request_serializer=AppRequest.SerializeToString,
          response_deserializer=AppResponse.FromString,
          )
      self.GetResponse1 = channel.stream_unary(
          '/Application/GetResponse1',
          request_serializer=AppRequest.SerializeToString,
          response_deserializer=AppResponse.FromString,
          )
      self.MultipleStream = channel.stream_stream(
          '/Application/MultipleStream',
          request_serializer=AppRequest.SerializeToString,
          response_deserializer=AppResponse.FromString,
          )


  class ApplicationServicer(object):

    def GetResponse(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetStreamedResponse(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetResponse1(self, request_iterator, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def MultipleStream(self, request_iterator, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ApplicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetResponse': grpc.unary_unary_rpc_method_handler(
            servicer.GetResponse,
            request_deserializer=AppRequest.FromString,
            response_serializer=AppResponse.SerializeToString,
        ),
        'GetStreamedResponse': grpc.unary_stream_rpc_method_handler(
            servicer.GetStreamedResponse,
            request_deserializer=AppRequest.FromString,
            response_serializer=AppResponse.SerializeToString,
        ),
        'GetResponse1': grpc.stream_unary_rpc_method_handler(
            servicer.GetResponse1,
            request_deserializer=AppRequest.FromString,
            response_serializer=AppResponse.SerializeToString,
        ),
        'MultipleStream': grpc.stream_stream_rpc_method_handler(
            servicer.MultipleStream,
            request_deserializer=AppRequest.FromString,
            response_serializer=AppResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Application', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaApplicationServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetResponse(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetStreamedResponse(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetResponse1(self, request_iterator, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def MultipleStream(self, request_iterator, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaApplicationStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetResponse(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    GetResponse.future = None
    def GetStreamedResponse(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    def GetResponse1(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    GetResponse1.future = None
    def MultipleStream(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()


  def beta_create_Application_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Application', 'GetResponse'): AppRequest.FromString,
      ('Application', 'GetResponse1'): AppRequest.FromString,
      ('Application', 'GetStreamedResponse'): AppRequest.FromString,
      ('Application', 'MultipleStream'): AppRequest.FromString,
    }
    response_serializers = {
      ('Application', 'GetResponse'): AppResponse.SerializeToString,
      ('Application', 'GetResponse1'): AppResponse.SerializeToString,
      ('Application', 'GetStreamedResponse'): AppResponse.SerializeToString,
      ('Application', 'MultipleStream'): AppResponse.SerializeToString,
    }
    method_implementations = {
      ('Application', 'GetResponse'): face_utilities.unary_unary_inline(servicer.GetResponse),
      ('Application', 'GetResponse1'): face_utilities.stream_unary_inline(servicer.GetResponse1),
      ('Application', 'GetStreamedResponse'): face_utilities.unary_stream_inline(servicer.GetStreamedResponse),
      ('Application', 'MultipleStream'): face_utilities.stream_stream_inline(servicer.MultipleStream),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Application_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Application', 'GetResponse'): AppRequest.SerializeToString,
      ('Application', 'GetResponse1'): AppRequest.SerializeToString,
      ('Application', 'GetStreamedResponse'): AppRequest.SerializeToString,
      ('Application', 'MultipleStream'): AppRequest.SerializeToString,
    }
    response_deserializers = {
      ('Application', 'GetResponse'): AppResponse.FromString,
      ('Application', 'GetResponse1'): AppResponse.FromString,
      ('Application', 'GetStreamedResponse'): AppResponse.FromString,
      ('Application', 'MultipleStream'): AppResponse.FromString,
    }
    cardinalities = {
      'GetResponse': cardinality.Cardinality.UNARY_UNARY,
      'GetResponse1': cardinality.Cardinality.STREAM_UNARY,
      'GetStreamedResponse': cardinality.Cardinality.UNARY_STREAM,
      'MultipleStream': cardinality.Cardinality.STREAM_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Application', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
